"""add summary to chat_sessions

Revision ID: 6f1e76fe3bbf
Revises: d9c07fe22541
Create Date: 2026-09-27 20:56:02.505057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1e76fe3bbf'
down_revision: Union[str, Sequence[str], None] = 'd9c07fe22541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'summary')
    # ### end Alembic commands ###
